name: Java Build and Deploy on develop

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
    types:
      - opened
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4
      # JDK 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v4

        with:
          java-version: '17'
          distribution: 'temurin'

      # application.yaml 생성
      - name: Create application.yaml
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_YAML }}" > src/main/resources/application.yaml
          echo "${{ secrets.APPLICATION_DEV_YAML }}" > src/main/resources/application-dev.yaml

      # Gradle 빌드
      - name: Build with Gradle
        run: |
          cd cloud
          chmod +x ./gradlew
          ./gradlew clean build -x test

      # Dcoker Hub 로그인
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Docker 이미지 빌드
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fit4u-backend ./cloud
      # Docker 이미지 푸시
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/fit4u-backend


      # EC2에 배포
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker ps
            sudo docker-compose down || true
            sudo docker-compose pull
            sudo docker-compose up -d
            sudo docker image prune -f
